unstable_features = true
indent_style = "Visual"
function_arguments = "Visual"
function_calls = "Visual"
fn_args_density = "Compressed"
fn_single_line = true
where_single_line = true
max_width = 140
merge_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
